### ISSUE TITLE
Support for container pebble layer defined externally

### ISSUE THREAD

**Issue by dimaqq** [canonical/ops-scenario#152]
I have this setup:

`rockcraft.yaml`

```yaml
services:
  gubernator:
    override: replace
    startup: enabled
    command: /bin/gubernator
    environment:
      GUBER_TRACING_LEVEL: ...
    on-success: shutdown
    on-failure: shutdown
    on-check-failure:
      online: shutdown
```

When juju starts a container with the image built from this rock, pebble gets this plan, and is started on hold, then charm does does:

```py
    def _on_gubernator_pebble_ready(self, event: ops.PebbleReadyEvent):
        event.workload.replan()
        self.unit.status = ops.ActiveStatus()
```

Meanwhile in unit tests, `scenario.mocking._MockPebbleClient` has a concept of containers, but is not instantiated with the layer data.

Which makes it kinda hard to test things, apart from happy path.

I wonder how to best represent this.
